/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.aplicacion_de_apuestas.frames;

import com.mycompany.aplicacion_de_apuestas.Corredor;
import com.mycompany.aplicacion_de_apuestas.Personas;
import java.util.ArrayList;

/**
 *
 * @author adria
 */
public class PanelCorredor extends javax.swing.JPanel {

    //ArrayList<Personas> listPersonas = new ArrayList<>();
    ArrayList<Corredor> listRuns = new ArrayList<>();
    Corredor corredor;
    
    public PanelCorredor() {
        initComponents();
    }
    public PanelCorredor(Corredor corredor,ArrayList<Corredor> listRuns){
      this.listRuns = listRuns;
      this.corredor = corredor;
        initComponents();
      jLabel1.setText(corredor.getNombre());
      labelId.setText(String.valueOf(listRuns.indexOf(corredor)+1));
      labelG.setText(""+corredor.getCarrerasG());//        ........
      labelApellido.setText(corredor.getApellido());
      labelAFavor.setText(""+corredor.getaFavor());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        labelId = new javax.swing.JLabel();
        labelG = new javax.swing.JLabel();
        labelApellido = new javax.swing.JLabel();
        labelAFavor = new javax.swing.JLabel();

        setBackground(new java.awt.Color(191, 12, 6));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        setForeground(new java.awt.Color(153, 255, 255));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("jLabel1");

        labelId.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelId.setForeground(new java.awt.Color(255, 255, 255));
        labelId.setText("jLabel2");

        labelG.setForeground(new java.awt.Color(255, 255, 255));
        labelG.setText("jLabel3");

        labelApellido.setForeground(new java.awt.Color(255, 255, 255));
        labelApellido.setText("jLabel2");

        labelAFavor.setForeground(new java.awt.Color(255, 255, 255));
        labelAFavor.setText("jLabel6");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addComponent(labelId)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelApellido)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 143, Short.MAX_VALUE)
                .addComponent(labelG)
                .addGap(82, 82, 82)
                .addComponent(labelAFavor)
                .addGap(19, 19, 19))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(labelId)
                    .addComponent(labelG)
                    .addComponent(labelApellido)
                    .addComponent(labelAFavor))
                .addContainerGap(15, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel labelAFavor;
    private javax.swing.JLabel labelApellido;
    private javax.swing.JLabel labelG;
    private javax.swing.JLabel labelId;
    // End of variables declaration//GEN-END:variables
}
    /* <dependency>
            <groupId>com.itextpdf</groupId>
            <artifactId>layout</artifactId>
            <version>8.0.3</version>
        </dependency>
        <dependency>
            <groupId>com.itextpdf</groupId>
            <artifactId>kernel</artifactId>
            <version>8.0.3</version>
        </dependency>*/
